spring.application.name=AppEcommerce
server.port=8080

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR


#spring.profiles.active=local
spring.profiles.active=docker

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=SECRET_2024
jwt.expiration=86400000 # 1 day in milliseconds

products.service.url=http://localhost:8080/api/product/search?id=
spring.datasource.initialization-mode=always
spring.sql.init.mode=always

